load("@rules_python//python:defs.bzl", "py_library")

cc_library(
    name = "lib-hello",
    srcs = [
        "hello.cc",
    ],
    hdrs = [
        "hello.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
