cc_test(
    name = "test-hello",
    size = "small",
    srcs = [
        "test-hello.cc",
    ],
    deps = [
        "//lib-hello",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test-world",
    size = "small",
    srcs = [
        "test-world.cc",
    ],
    deps = [
        "//lib-world",
        "@gtest//:gtest_main",
    ],
)
